<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$lang['general_terms_of_use_sugarbabe_deluxe'] = 'Condizioni generali d\'uso Sugarbabe Deluxe';

$lang['general'] = 'Generale';
$lang['general_rule_one'] = 'Sugarbabe Deluxe (www.sugarbabe-deluxe.eu - di seguito "il servizio") è un servizio della rete di ordini e.U., Gewerbepark 1 / Top16, 5222 Munderfing (di seguito "l\'operatore").';
$lang['general_rule_two'] = 'Registrandosi al Servizio, l\'utente accetta le presenti Condizioni d\'uso per l\'uso del Servizio (di seguito "Condizioni d\'uso"). L\'operatore fornisce il servizio esclusivamente sulla base delle condizioni di utilizzo nella loro versione valida al momento della registrazione dell\'utente.';
$lang['general_rule_three'] = 'Il servizio, i suoi contenuti e i dati accessibili attraverso il servizio sono disponibili all\'utente per scopi puramente privati ​​o non commerciali. È vietato qualsiasi utilizzo per altri scopi, in particolare per scopi commerciali o commerciali.';
$lang['general_rule_four'] = 'Gli utenti del servizio possono essere solo adulti (oltre 18 anni). Il servizio non è aperto a minori di 18 anni. Registrandosi per il servizio, l\'utente assicura di avere almeno 18 anni.';

$lang['services'] = 'Servizi';
$lang['services_rule_one'] = 'L\'operatore offre all\'utente l\'accesso al suo database. Questo database consente all\'utente di creare collaborazioni e amicizie con altri membri. Contiene anche profili e informazioni su altri utenti. Gli utenti possono visualizzare i profili degli altri utenti nel database ed essere contattati da loro in misura limitata e creare il proprio profilo tra cui foto e fino a 12 album di foto del profilo, 12 album di immagini VIP e 12 album di immagini private e inseriti nel database. Il cliente appare solo ai clienti terzi con un nome anonimo desiderato. Gli utenti hanno anche l\'opportunità di aggiornare il loro abbonamento gratuito esistente a un "abbonamento VIP" pagato. Oltre alle funzioni dell\'appartenenza di base gratuita, sono disponibili funzioni aggiuntive per un "membro VIP". Tra le altre cose, un "membro VIP" ha accesso al sistema di messaggistica del servizio e può scrivere messaggi ad altri "membri VIP" gratuitamente. Inoltre, un "membro VIP" può sbloccare 12 membri di base mensilmente per il contatto. L\'attivazione ha una durata limitata di un mese. L\'accesso completo all\'album fotografico VIP verrà fornito anche ai "membri VIP".';
$lang['services_rule_two'] = 'L\'oggetto del contratto non è l\'intermediazione matrimoniale. L\'operatore non promette contatti di successo con altri utenti del servizio. L\'oggetto del servizio è solo il - a seconda della natura dell\'appartenenza acquisita diversamente progettato - la possibilità di stabilire un contatto con gli utenti del servizio.';

$lang['license_agreement'] = 'Accordo di licenza';
$lang['license_agreement_rule_one'] = 'L\'utilizzo del servizio è possibile solo previa registrazione da parte dell\'utente e accettazione della registrazione da parte dell\'operatore. L\'oggetto dei contratti utente è in ogni caso l\'utilizzo dei servizi da parte dell\'utente nell\'ambito dell\'iscrizione selezionata. Gli utenti hanno due opzioni per l\'utilizzo del servizio o dell\'iscrizione: 1. Uso gratuito e limitato del servizio come parte dell\'appartenenza di base (in seguito denominata "iscrizione di base"); 2. utilizzo esteso e a pagamento del servizio nell\'ambito delle iscrizioni VIP (di seguito "adesione VIP"). Ciò richiede una registrazione precedente come membro di base. L\'utente deve prima accedere al servizio come membro di base. Quindi l\'utente ha l\'opportunità di ordinare un abbonamento VIP a pagamento. La descrizione delle iscrizioni, la loro portata dei servizi così come i prezzi delle iscrizioni VIP devono essere prese dalle presentazioni nel contesto del servizio.';
$lang['license_agreement_rule_two'] = 'La possibilità di utilizzare il servizio offerto o la possibilità di registrazione o registrazione per il servizio - sia gratuita (iscrizione di base) o quota (iscrizione VIP) - non è vincolante e, in particolare, non costituisce un\'offerta vincolante dell\'operatore per concludere una corrispondente contratto di licenza Piuttosto, è una richiesta all\'utente di presentare un\'offerta per concludere un contratto utente da vedere. Al termine della rispettiva procedura di registrazione o ordine da parte dell\'utente sul portale Internet del servizio, quest\'ultimo offre un\'offerta vincolante per la conclusione del contratto (abbonamento base o iscrizione VIP) sull\'utilizzo del servizio. L\'operatore può accettare questa offerta dell\'utente tramite e-mail separata o fornendo il servizio corrispondente entro tre giorni lavorativi, altrimenti l\'utente non è più vincolato dalla sua offerta. Solo con questa assunzione il contratto tra l\'utente e l\'operatore si stacca. L\'operatore non è obbligato a concludere il contratto. L\'operatore può rifiutare l\'accettazione della registrazione o dell\'ordine (conclusione del contratto) senza indicarne i motivi.';

$lang['rights_and_obligations'] = 'Diritti e doveri';
$lang['rights_and_obligations_rule_one'] = 'Al momento della registrazione per l\'iscrizione di base, la nomina di un abbonamento VIP e la creazione del profilo utente, vengono richiesti vari dettagli dell\'utente. Questi possono essere obbligatori e facoltativi. L\'utente assicura che le informazioni fornite da lui sono in ogni caso complete e corrette, e che in particolare i dati di contatto da lui depositati sono validi e assegnati a lui. L\'utente è obbligato ad adattare le modifiche riguardanti le informazioni richieste da lui immediatamente inserite nel profilo.';
$lang['rights_and_obligations_rule_two'] = 'È vietato agli utenti comunicare i dati di accesso a terzi o consentire a terzi di utilizzare i servizi con i dati di accesso dell\'utente. L\'utente è tenuto a mantenere i propri dati di accesso per l\'utilizzo del servizio generalmente segreto. Se l\'utente ha motivo di sospettare che una terza persona possa aver acquisito conoscenza dei suoi dati di accesso, deve informare immediatamente l\'operatore e cambiare la sua password.';
$lang['rights_and_obligations_rule_three'] = 'L\'utente deve astenersi da:';
$lang['rights_and_obligations_rule_three_one'] = 'La pubblicazione di qualsiasi tipo di contenuto che violi qualsiasi legge applicabile, viola i diritti di terzi o viola i principi della protezione della gioventù in particolare:';
$lang['rights_and_obligations_rule_three_one_one'] = 'L\'uso di contenuti che danneggiano o malignano altri utenti o terze parti;';
$lang['rights_and_obligations_rule_three_one_two'] = 'L\'uso, la preparazione e la preparazione di contenuti, servizi e / o prodotti che sono protetti dalla legge o con diritti di terzi (ad es. Urheberrechte) belasetet senza essere espressamente autorizzato a ciò;';
$lang['rights_and_obligations_rule_three_one_three'] = 'La costituzione, la distribuzione, l\'offerta e l\'applicazione di poro-nogra fi, contro la protezione dei minori, contro i diritti di protezione dei dati e / o o contro altri diritti di violazione e / o contenuti fraudolenti, servizi e / o prodotti.';
$lang['rights_and_obligations_rule_three_two'] = 'Indipendente da un\'eventuale violazione della legge in caso di costituzione di propri contenuti nell\'ambito del servizio, nonché nella comunicazione con gli altri utenti (ad esempio, eliminando gli effetti personali, partecipando a processi di disinfezione o rilevamento) di voci del libro degli ospiti) i seguenti elementi attivi:';
$lang['rights_and_obligations_rule_three_two_one'] = 'Per ulteriori chiarimenti ad altri utenti per la divulgazione di identificatori o mediante dati personali per scopi commerciali o non appiccicosi;';
$lang['rights_and_obligations_rule_three_two_two'] = 'Belese ting un\'altra parte, e. rendere più contatti con o senza la risposta dell\'altro utente, così come la promozione o il supporto degli assistenti del lavoratore;';
$lang['rights_and_obligations_rule_three_two_three'] = 'Cessione e / o pubblicità Come la messa a disposizione o la messa a disposizione del pubblico del contenuto del servizio, a meno che ciò non sia espressamente consentito dal rispettivo copyright o come radioattività nel contesto, il servizio è espressamente fornito;';
$lang['rights_and_obligations_rule_three_two_four'] = 'Contenuti o comunicazioni sproporzionati, sessualmente influenzati, osceni o diffe- renziati, nonché contenuti o comunicazioni che sono / sono idonei all\'uso, ras sis mus, Fana tis mus, odio, violenza corporale o atti di destra da promuovere o sostenere (in ogni caso esplicitamente o implicitamente);';
$lang['rights_and_obligations_rule_three_two_five'] = 'Distribuzione di virus, virus e altri file dannosi;';
$lang['rights_and_obligations_rule_three_two_six'] = 'Invio di e-mail indesiderate o spam e invio di lettere.';
$lang['rights_and_obligations_rule_three_two_seven'] = 'La riproduzione, la visualizzazione o altra indicazione dei dati di contatto (ad esempio numero di telefono, indirizzi, indirizzi e-mail, ecc.) Visibili nel contesto del servizio per altri utenti del servizio o altre informazioni (ad es. Collegamenti a profili dell\'utente su altri social network o altri servizi, nomi utente su altri social network o altri servizi, ecc.) che possono essere utilizzati per contattare gli utenti del servizio bypassando il servizio oi relativi sistemi di messaggistica.';
$lang['rights_and_obligations_rule_three_three'] = 'Qualsiasi azione che possa influire sul funzionamento improprio del servizio e, in particolare, per sovraccaricare eccessivamente i sistemi dell\'operatore.';
$lang['rights_and_obligations_rule_three_four'] = 'Qualsiasi utilizzo del servizio, dei suoi contenuti o dei dati disponibili per gli scopi del servizio a fini commerciali o commerciali, in particolare qualsiasi contatto con altri destinatari del servizio nel contesto del servizio per gli scopi di cui sopra.';
$lang['rights_and_obligations_rule_three_five'] = 'Leggere o copiare sistematicamente o altrimenti esportare i contenuti del servizio o i dati degli utenti del servizio per utilizzarli al di fuori del servizio.';

$lang['availability'] = 'Disponibilità';
$lang['availability_info_text'] = 'Se è prevedibile per l\'operatore che impiega più di 2 ore, il fornitore informerà il cliente almeno 2 giorni di calendario prima dell\'inizio del rispettivo lavoro. Fondamentalmente, il servizio è operativo 24 ore al giorno, sette giorni alla settimana, con una disponibilità del 99% su una media mensile. Ciò esclude i tempi di inattività dovuti a manutenzione e aggiornamenti del software, nonché i tempi in cui non è possibile accedere al server web via Internet a causa di problemi tecnici o di altro tipo che esulano dal controllo dell\'operatore (forza maggiore, colpa di terzi, ecc.) .';

$lang['content'] = 'Soddisfare';
$lang['content_rule_one'] = 'L\'utente è il solo e completamente responsabile del contenuto che ha fornito. L\'operatore non intraprende alcuna revisione dei contenuti per completezza, accuratezza, legalità, attualità, qualità e idoneità per uno scopo particolare. L\'utente assicura l\'operatore e garantisce di essere il solo autorizzato a disporre del contenuto che ha pubblicato, in particolare che ha il diritto di concedere all\'operatore i diritti concessi qui e che non ha effettuato o prende alcuna disposizione contraria ai diritti contrattuali diventa. L\'utente manleva l\'operatore da tutte le pretese di terzi in connessione con l\'uso contrattuale dei contenuti, compresi i costi di un\'adeguata difesa legale, in alternativa lo indennizza. Questo non si applica se l\'utente non è responsabile della violazione.';
$lang['content_rule_two'] = 'L\'operatore si riserva il diritto di rifiutare la pubblicazione di contenuti da parte dell\'utente e / o contenuti già contenuti (inclusi in particolare e-mail prioritaria, voci del libro degli ospiti e altre comunicazioni). senza preavviso, blocco o rimozione, a condizione che la pubblicazione di contenuti da parte dell\'utente o del contenuto stesso abbia portato a una violazione delle presenti Condizioni d\'uso o alla prova concreta che sarà difficile violare le presenti Condizioni d\'uso. Tuttavia, l\'operatore esaminerà i legittimi interessi dell\'utente e sceglierà i mezzi per difendere il reato.';
$lang['content_rule_three'] = 'Impostando il contenuto nell\'ambito del servizio, l\'utente concede all\'operatore in ogni caso un diritto d\'uso incondizionato e acquisito nel rispettivo contenuto, in particolare.';
$lang['content_rule_three_one'] = 'Per l\'archiviazione del contenuto sul server dell\'operatore e la sua pubblicazione, in particolare la loro accessibilità pubblica (ad esempio visualizzando il contenuto su Internet come parte del servizio),';
$lang['content_rule_three_two'] = 'Per il trattamento e la copia nella misura necessaria per la preparazione o la pubblicazione del suo contenuto, e';
$lang['content_rule_three_three'] = 'Per l\'inclusione - anche a pagamento - dei diritti di utilizzo nei confronti di terzi nel contesto dell\'utilizzo del servizio.';
$lang['content_rule_three_four'] = 'Il suddetto diritto di utilizzo scade se e non appena l\'utente rimuove il contenuto che ha pubblicato e il servizio. Tuttavia, l\'operatore conserva il diritto di memorizzare copie dei contenuti creati a scopo di backup e / o verifica. Rimangono inalterati anche i terzi utenti dei contenuti regolati dall\'utente, i diritti di utilizzo precedentemente archiviati.';

$lang['duration_and_termination'] = 'Durata e risoluzione';
$lang['duration_and_termination_rule_one'] = 'L\'iscrizione di base viene eseguita a tempo indeterminato e può essere modificata dall\'utente in qualsiasi momento. L\'operatore può rescindere l\'iscrizione di base con un preavviso di 14 giorni di calendario fino alla fine del mese';
$lang['duration_and_termination_rule_two'] = 'Le iscrizioni VIP sono offerte con termini di 1, 3 e 6 mesi. Dettagli possono essere trovati nella rispettiva descrizione del prodotto. Nel caso di un abbonamento VIP con un termine di 1 mese, l\'iscrizione verrà estesa di un mese se l\'utente non cancella l\'iscrizione tramite e-mail o nel profilo utente facendo clic sul pulsante di cancellazione almeno 24 ore prima la fine dell\'iscrizione (compresi i periodi di estensione facoltativi) termina o l\'operatore non annulla per iscritto entro 3 giorni di calendario prima della scadenza dell\'iscrizione (compresi i periodi di estensione facoltativi), tramite e-mail. Per le iscrizioni ai VIP di più di un mese di durata iniziale (3 e 6 mesi), l\'iscrizione verrà estesa per il periodo originariamente prenotato (rispettivamente 3 o 6 mesi) se l\'utente non annulla l\'iscrizione almeno una settimana prima della fine dell\'iscrizione (compresi i periodi di rinnovo facoltativi) per iscritto via e-mail o nel profilo utente facendo clic sul pulsante di notifica termina o l\'operatore non almeno 2 settimane prima della scadenza dell\'iscrizione (compresi periodi di estensione facoltativi) per iscritto via e-mail annuncia . Decisivo per l\'inizio dell\'appartenenza è l\'accettazione della registrazione dell\'utente da parte dell\'operatore (conclusione del contratto).';
$lang['duration_and_termination_rule_three'] = 'Il diritto delle parti di risolvere il contratto per giusta causa non è influenzato dalle disposizioni di risoluzione di cui sopra.';
$lang['duration_and_termination_rule_four'] = 'La relazione contrattuale termina con l\'effetto della cancellazione e l\'utente non può più utilizzare l\'accesso contrattato. L\'operatore ha il diritto di bloccare il nome utente e la password con l\'effetto della restrizione.';
$lang['duration_and_termination_rule_five'] = 'L\'operatore ha diritto, allo scadere di 30 giorni di calendario dall\'efficacia dell\'esercizio e dopo la scadenza di qualsiasi termine legale, di completare la procedura nel contesto dell\'utilizzo del servizio da parte dell\'utente, i dati devono essere cancellati senza indebito ritardo .';

$lang['blocking'] = 'Blocco';
$lang['blocking_rule_one'] = 'Se l\'utente viola questo diritto d\'uso e / o ha violato la legge, o se l\'operatore ha un interesse legittimo nel blocco, l\'operatore può L\'accesso dell\'utente al servizio può essere temporaneamente o permanentemente sospeso. In caso di decisione sulla sospensione, l\'operatore deve tener conto dei ragionevoli interessi dell\'utente.';
$lang['blocking_rule_two'] = 'In caso di blocco temporaneo o permanente, l\'operatore blocca l\'autorizzazione all\'accesso e informa l\'utente via e-mail. Mail.';
$lang['blocking_rule_three'] = 'Nel caso di un\'inibizione, l\'operatore reagisce dopo aver effettuato l\'accesso al periodo di blocco e avvisa l\'utente di questo tramite e-mail. Un\'autorizzazione di accesso bloccata in modo permanente non può essere ristabilita. Gli utenti bloccati in permanenza sono permanentemente esclusi dalla partecipazione al servizio e potrebbero non registrarsi nuovamente al servizio.';

$lang['payment'] = 'Pagamento';
$lang['payment_rule_one'] = 'I seguenti metodi di pagamento sono disponibili per l\'utente:';
$lang['payment_rule_one_one'] = 'Sofortüberweisung: al termine della prenotazione, l\'utente verrà reindirizzato al modulo di pagamento sicuro SOFORT per effettuare il trasferimento. La registrazione non è richiesta. I dati vengono trasmessi crittografati e il trasferimento viene effettuato direttamente.';
$lang['payment_rule_one_two'] = 'Addebito diretto: nel sistema di addebito diretto, l\'importo della fattura viene addebitato in modo semplice e conveniente dall\'account entro otto giorni lavorativi utilizzando i dati dell\'account forniti dall\'utente. Il beneficiario sarà indicato nel libro paga come "Contratto netto e.U."';
$lang['payment_rule_one_three'] = 'Carta di credito: l\'operatore accetta Visa, Mastercard. La carta di credito verrà addebitata al completamento del contratto (accettazione della domanda). Il beneficiario verrà visualizzato nella fatturazione: XXX';
$lang['payment_rule_two'] = 'Gli utenti non sono autorizzati a compensare le pretese dell\'operatore, a meno che le domande riconvenzionali dell\'utente siano legalmente stabilite o indiscusse. L\'utente ha anche il diritto di compensare le pretese dell\'operatore se l\'utente dichiara controdeduzioni dallo stesso contratto. L\'utente può esercitare un diritto di ritenzione solo se la sua domanda riconvenzionale risulta dallo stesso contratto.';

$lang['liability'] = 'Responsabilità';
$lang['liability_rule_one'] = 'L\'operatore è responsabile per violazione intenzionale e gravemente negligente del dovere - per qualsiasi motivo legale - in conformità con le disposizioni di legge.';
$lang['liability_rule_two'] = 'L\'operatore è responsabile per semplice negligenza solo per i danni derivanti dalla violazione di un obbligo contrattuale. Obblighi contrattuali essenziali sono quelli il cui adempimento rende possibile la corretta esecuzione del contratto in primo luogo e sulla cui conformità lutente si fida regolarmente e può fare affidamento. In caso di violazione di obblighi contrattuali essenziali, l\'obbligo di risarcimento è limitato al danno tipicamente prevedibile al momento della conclusione del contratto.';

$lang['services'] = 'Servizi';
$lang['services_info_text'] = 'Le informazioni sulla protezione dei dati sono disponibili nell\'informativa sulla privacy XXX (Link) separata, che non fa parte del contratto ma è conforme ai doveri di informazione del DSGVO.';

$lang['amendments'] = 'Modifiche';
$lang['amendments_info_text'] = 'Queste condizioni d\'uso possono essere modificate in qualsiasi momento con efficacia anche all\'interno dei rapporti contrattuali esistenti. Il diritto delle parti contraenti di risolvere il contratto rimane inalterato. Se l\'operatore intende modificare queste condizioni d\'uso, l\'operatore informerà l\'utente almeno 8 settimane prima dell\'entrata in vigore prevista delle modifiche. Se l\'utente non si oppone entro 6 settimane (periodo di obiezione) dal ricevimento della notifica della modifica, si presume che la modifica sia stata validamente concordata alla scadenza del periodo di opposizione. L\'obiezione deve essere fatta per e-mail o per iscritto. L\'operatore indicherà questa sequenza separatamente nella notifica di modifica. Se l\'utente esercita il proprio diritto di obiezione, la richiesta di modifica è considerata respinta. Il contratto proseguirà quindi senza la modifica proposta.';

$lang['cancellation'] = 'Cancellazione';
$lang['cancellation_rule_one_info'] = 'Hai il diritto di stipulare questo contratto entro quattordici giorni senza dare alcuna motivazione. Il periodo di revoca è di quattordici giorni dalla data del contratto. Per esercitare il diritto di recesso, è necessario (ordinare rete eU, Gewerbepark 1 / Top 16, 5222 Munderfing, e-mail: support@sugarbabe-deluxe.eu) mediante una dichiarazione chiara (ad esempio una lettera inviata per posta o e-mail) informa sulla tua decisione di recedere dal presente contratto. È possibile utilizzare il modulo di recesso del modello allegato, che non è richiesto. Per mantenere il periodo di cancellazione, è sufficiente che tu invii l\'avviso dell\'esercizio del diritto di recesso prima della scadenza del periodo di recesso.';
$lang['cancellation_rule_two'] = 'Conseguenze della cancellazione';
$lang['cancellation_rule_two_info'] = 'In caso di recesso dal presente Accordo, abbiamo selezionato tutti i pagamenti che abbiamo ricevuto da voi, comprese le spese di spedizione (ad eccezione dei costi aggiuntivi derivanti dalla scelta di un metodo di consegna diverso rispetto alla consegna standard più favorevole che offriamo di rimborsare immediatamente e al entro quattordici giorni dalla data in cui la notifica della revoca del presente contratto ci è pervenuta.Per questo rimborso, utilizziamo lo stesso mezzo di pagamento utilizzato nella transazione originale, salvo diversamente concordato con te, in nessun caso ti verranno addebitate le spese di rimborso: se hai richiesto che i servizi siano iniziati durante il periodo di cancellazione, devi pagarci un importo ragionevole pari alla proporzione di servizi già forniti da te nel momento in cui ci comunichi dell\'esercizio di il diritto di recesso in relazione a questo contratto Confronto con il volume totale dei servizi previsti nel contratto.';
$lang['cancellation_rule_three'] = 'Modulo di recesso del modello (Se si desidera annullare il contratto, si prega di compilare questo modulo e inviarlo di nuovo.):';
$lang['on'] = 'Sopra:';
$lang['cancellation_rule_form_one'] = 'I / we (*) con la presente revocano il contratto concluso da me / noi (*) per l\'acquisto dei seguenti prodotti (*) / la fornitura del seguente servizio (*)';
$lang['cancellation_rule_form_two'] = 'Ordinato su (*) / ricevuto su (*):';
$lang['cancellation_rule_form_three'] = 'Nome del / i consumatore / i:';
$lang['cancellation_rule_form_four'] = 'Indirizzo del / dei consumatore / i:';
$lang['cancellation_rule_form_five'] = 'Firma del / dei consumatore / i (solo se notificato su supporto cartaceo):';
$lang['cancellation_rule_form_six'] = 'Data:';
$lang['cancellation_rule_form_seven'] = '(*) Cancellare come appropriato.';

$lang['final_provisions'] = 'Disposizioni finali';
$lang['final_provisions_rule_one'] = 'Tutte le transazioni legali sono regolate dalla legge austriaca, ad eccezione della Convenzione delle Nazioni Unite sulle vendite.';
$lang['final_provisions_rule_two'] = 'La giurisdizione è - per quanto consentito dalla legge - Braunau. Indipendentemente da ciò, l\'operatore ha il diritto di citare in giudizio l\'utente nel suo luogo di giurisdizione generale.';
$lang['final_provisions_rule_three'] = 'Oltre alla procedura ordinaria, i consumatori hanno anche la possibilità di risolvere le controversie in via extragiudiziale conformemente al regolamento (UE) n. 524/2013. I dettagli possono essere trovati lì e all\'indirizzo Internet:';