<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$lang['general_terms_of_use_sugarbabe_deluxe'] = 'General Terms of Use Sugarbabe Deluxe';

$lang['general'] = 'General';
$lang['general_rule_one'] = 'Sugarbabe Deluxe (www.sugarbabe-deluxe.eu - hereinafter referred to as "the service") is a service of the order network e.U., Gewerbepark 1 / Top16, 5222 Munderfing (hereinafter referred to as "the operator").';
$lang['general_rule_two'] = 'By registering with the Service, the user accepts these Terms of Use for Use of the Service (hereinafter referred to as "the Terms of Use"). The operator provides the service exclusively on the basis of the terms of use in their version valid at the time of the user\'s registration.';
$lang['general_rule_three'] = 'The service, its contents and the data accessible through the service are available to the user for purely private or non-commercial purposes. Any use for other purposes, in particular for commercial or commercial purposes, is prohibited.';
$lang['general_rule_four'] = 'Users of the service can only be adults (over 18 years). The service is not open to persons under 18 years. By registering for the service, the user assures to be at least 18 years old.';

$lang['services'] = 'Services';
$lang['services_rule_one'] = 'The operator offers the user access to his database. This database allows the user to build partnerships and friendships with other members. It also contains profiles and information about other users. Users can view the profiles of other users in the database and be contacted by them to a limited extent and create their own profile including photo and up to 12 profile pictures album, 12 VIP images album and 12 private images album and put into the database. The customer only appears to third customers under an anonymous desired name. Users also have the opportunity to upgrade their existing free membership to a paid "VIP membership". In addition to the functions of the free basic membership, additional functions are available to a "VIP member". Among other things, a "VIP member" has access to the messaging system of the service and can write messages to other "VIP members" free of charge. In addition, a "VIP member" can unlock 12 base members monthly for contact. The activation has a limited term of one month. Full access to the VIP Photo Album will also be provided to "VIP Members".';
$lang['services_rule_two'] = 'The subject of the contract is not marriage brokerage. The operator does not promise successful contact with other users of the service. Subject of the service is only the - depending on the nature of the acquired membership differently designed - the possibility of establishing contact with the users of the service.';

$lang['license_agreement'] = 'License Agreement';
$lang['license_agreement_rule_one'] = 'The use of the service is only possible after prior registration by the user and acceptance of the registration by the operator. The subject matter of the user contracts is in each case the use of the services by the user within the scope of the selected membership. Users have two options for using the service or membership: 1. Free, limited use of the service as part of the basic membership (hereinafter referred to as "basic membership"); 2. extended, paid use of the service within the scope of the VIP memberships (hereinafter referred to as "VIP memberships"). This requires a previous registration as a basic member. The user must first log in to the service as a basic member. Then the user has the opportunity to order a paid VIP membership. The description of the memberships, their scope of services as well as the prices of the VIP memberships are to be taken from the presentations in the context of the service.';
$lang['license_agreement_rule_two'] = 'The possibility of using the service offered or the possibility of registration or registration for the service - whether free (basic membership) or fee (VIP membership) - is not binding and in particular does not constitute a binding offer of the operator to conclude a corresponding license agreement Rather, it is a request to the user to submit an offer to conclude a user contract to see. Upon completion of the respective registration or order process by the user on the Internet portal of the service, the latter makes a binding offer to conclude the contract (basic membership or VIP membership) on the use of the service. The operator may accept this offer of the user by separate e-mail or by providing the corresponding service within three working days, otherwise the user is no longer bound by his offer. Only by this assumption the contract between the user and the operator comes off. The operator is not obliged to conclude the contract. The operator can refuse the acceptance of the registration or order (conclusion of the contract) without stating reasons.';

$lang['rights_and_obligations'] = 'Rights and Obligations';
$lang['rights_and_obligations_rule_one'] = 'When registering for the basic membership, the appointment of a VIP membership and the creation of the user profile, various details of the user are requested. These can be mandatory as well as optional. The user assures that the information provided by him is in any case complete and correct, and that in particular the contact data deposited by him are valid and assigned to him. The user is obligated to adapt changes regarding the required information given by him immediately in the profile.';
$lang['rights_and_obligations_rule_two'] = 'It is forbidden for users to communicate the access data to third parties or to enable third parties to use the services with access data of the user. The user is obliged to keep his access data for the use of the service generally secret. If the user has reason to suspect that a third party may have gained knowledge of his access data, he must notify the operator without delay and change his password.';
$lang['rights_and_obligations_rule_three'] = 'The user has to refrain from:';
$lang['rights_and_obligations_rule_three_one'] = 'The publication of any kind of content that violates any applicable law, infringes the rights of third parties, or violates the principles of youth protection in particular:';
$lang['rights_and_obligations_rule_three_one_one'] = 'The use of content that damages or maligns other users or third parties;';
$lang['rights_and_obligations_rule_three_one_two'] = 'The use, the preparation and the preparation of contents, services and / or products which are protected by law or with rights of third parties (eg Urheberrechte) belastet without being expressly entitled thereto;';
$lang['rights_and_obligations_rule_three_one_three'] = 'The setting up, the distribution, the offer and the application of poro-nogra fi, against protection of minors, against data protection rights and / or or against other rights of infringing and / or fraudulent content, services and / or products.';
$lang['rights_and_obligations_rule_three_two'] = 'Independent of a possible infringement of the law in the case of the establishment of own contents within the scope of the service as well as in the communication with others Users (for example, by eliminating personal effects, by participating in disinfecting or detecting processes) of guest book entries) the following active items:';
$lang['rights_and_obligations_rule_three_two_one'] = 'For further explanation to other users for the disclosure of identifiers or by means of a personal data for commerce or right- or non-sticky purposes;';
$lang['rights_and_obligations_rule_three_two_two'] = 'Belese ting another part, e. making more con tacts with or without the response of the other user, as well as the promotion or support of the worker\'s carers;';
$lang['rights_and_obligations_rule_three_two_three'] = 'Assignment and / or publicity Such as the making available or making available to the public of the content of the service, unless this is expressly permitted by the respective copyright or as radioactivity within the context the service is expressly provided;';
$lang['rights_and_obligations_rule_three_two_four'] = 'Disproportionate, sexually influenced, obscene or diffe- rentiated content or communication as well as content or communication that is / are fit for use, ras sis mus, Fana tis mus, hate, corporal violence or right-wing acts to promote or support (in each case explicitly or implicitly);';
$lang['rights_and_obligations_rule_three_two_five'] = 'Distribution of viruses, viruses and other harmful files;';
$lang['rights_and_obligations_rule_three_two_six'] = 'Sending junk or spam e-mails and sending letters.';
$lang['rights_and_obligations_rule_three_two_seven'] = 'The reproduction, display or other indication of contact data (eg telephone number, addresses, e-mail addresses, etc.) visible in the context of the service for other users of the service or other information (eg links to profiles of the user on other social networks or other Services, usernames on other social networks or other services, etc.) that may be used to contact users of the service bypassing the service or its messaging systems.';
$lang['rights_and_obligations_rule_three_three'] = 'Any action likely to affect the improper operation of the service and, in particular, to overburden the operator\'s systems excessively.';
$lang['rights_and_obligations_rule_three_four'] = 'Any use of the service, its contents or the data available for the purposes of the service for commercial or commercial purposes, in particular any contact with or other addressing of other users of the service in the context of the service for the aforementioned purposes.';
$lang['rights_and_obligations_rule_three_five'] = 'Systematically read or copy or otherwise export the contents of the service or data of the users of the service in order to use them outside of the service.';

$lang['availability'] = 'Availability';
$lang['availability_info_text'] = 'If it is foreseeable for the operator that takes more than 2 hours, the provider will notify the customer at least 2 calendar days before the start of the respective work. Basically, the service is operational 24 hours a day, seven days a week, with an availability of 99% on a monthly average. This excludes downtime due to maintenance and software updates as well as times when the web server can not be accessed via the Internet due to technical or other problems that are beyond the control of the operator (force majeure, fault of third parties, etc.).';

$lang['content'] = 'Content';
$lang['content_rule_one'] = 'The user is solely and completely responsible for the content he has provided. The operator does not undertake any review of the contents for completeness, accuracy, legality, actuality, quality and suitability for a particular purpose. The user assures the operator and warrants that he is sole authorized to dispose of the content he has posted, in particular that he is entitled to grant the operator the rights granted here and that he has not made or takes any disposition contrary to the contractual rights becomes. The user indemnifies the operator from all claims of third parties in connection with the contractual use of the contents, including the costs of appropriate legal defense, in the alternative, he indemnifies him. This does not apply if the user is not responsible for the infringement.';
$lang['content_rule_two'] = 'The operator reserves the right to refuse the posting of content by the user and / or already contained content (including in particular pri va ry e-mail, guest book entries and other communications). without prior notification, blocking or removal, provided that the posting of content by the user or the content itself has led to a breach of these Terms of Use or concrete evidence that it will be difficult to violate these Terms of Use. However, the operator will look at the user\'s legitimate interests and choose the means to defend the offense.';
$lang['content_rule_three'] = 'By setting up content within the scope of the service, the user grants the operator in each case an unconditional and vested right of use in the respective content, in particular.';
$lang['content_rule_three_one'] = 'For the storage of the content on the server of the operator and its publication, in particular their public accessibility (for example by displaying the content on the Internet as part of the service),';
$lang['content_rule_three_two'] = 'For processing and copying to the extent necessary for the preparation or publication of the content thereof, and';
$lang['content_rule_three_three'] = 'For the inclusion of - also payable - rights of use against third parties in the context of the use of the service.';
$lang['content_rule_three_four'] = 'The above right of use expires if and as soon as the user removes the content he has posted as well as the service. However, the operator retains the right to store copies of the contents created for the purpose of backup and / or verification. The third users of user-adjusted content previously stored rights of use remain also unaffected.';

$lang['duration_and_termination'] = 'Duration and Termination';
$lang['duration_and_termination_rule_one'] = 'The basic membership runs indefinitely and can be changed by the user at any time. The operator may terminate the basic membership by giving notice of 14 calendar days to the end of the month';
$lang['duration_and_termination_rule_two'] = 'The VIP memberships are offered with terms of 1, 3 and 6 months. Details can be found in the respective product description. In the case of a VIP membership with a term of 1 month, the membership will be extended by one month if the user does not cancel the membership by e-mail or in the user profile by clicking the cancellation button at the latest 24 hours before the end of the membership (including optional extension periods) terminates or the operator does not cancel in writing at the latest 3 calendar days before expiration of the membership (including optional extension periods), by email. For VIP memberships of more than one month of initial term (3 and 6 months), the membership will be extended by the originally booked period (3 or 6 months respectively) if the user does not cancel the membership at least one week before the end of the membership (including optional renewal periods) in writing by email or in the user profile by clicking on the notice button terminates or the operator not at least 2 weeks before the expiration of the membership (including optional extension periods) in writing via email announces. Decisive for the beginning of membership is acceptance of the user\'s registration by the operator (conclusion of contract).';
$lang['duration_and_termination_rule_three'] = 'The right of the parties to terminate the contract for good cause is not affected by the above termination provisions.';
$lang['duration_and_termination_rule_four'] = 'The contracting relationship ends with the effect of the cancellation and the user may no longer use the contracted access. The operator is entitled to block the user name as well as the password with the effect of the restriction.';
$lang['duration_and_termination_rule_five'] = 'The operator is entitled, at the expiration of 30 calendar days after the effectiveness of the exercise and after expiry of any legal deadlines, to complete the procedure In the context of the use of the service by the user, data must be deleted without undue delay.';

$lang['blocking'] = 'Blocking';
$lang['blocking_rule_one'] = 'If the user infringes this right of use and / or has violated the law, or if the operator has a legitimate interest in the lock, the operator may Access of the user to the service may be temporarily or permanently suspended. In the event of a decision on a suspension, the operator shall take into account the reasonable interests of the user.';
$lang['blocking_rule_two'] = 'In the event of a temporary or permanent blockage, the operator blocks the access authorization and informs the user about this via e-mail. Mail.';
$lang['blocking_rule_three'] = 'In the case of an inhibition, the operator reacts after accessing the blocking period and notifies the user about this by email. A permanently blocked access authorization can not be re-established. Permanently barred users are permanently excluded from participation in the service and may not re-register with the service.';

$lang['payment'] = 'Payment';
$lang['payment_rule_one'] = 'The following payment methods are available to the user:';
$lang['payment_rule_one_one'] = 'Sofortüberweisung: At the end of the booking, the user will be redirected to the secure SOFORT payment form to make the transfer. Registration is not required. The data is transmitted encrypted and the transfer is made directly.';
$lang['payment_rule_one_two'] = 'Direct debit: In the direct debit system, the invoice amount is simply and conveniently debited from the account within eight working days using the account data provided by the user. The payee will be shown on the payroll as: "Contract net e.U."';
$lang['payment_rule_one_three'] = 'Credit card: The operator accepts Visa, Mastercard. The credit card will be charged upon completion of the contract (acceptance of the application). The payee will be shown on the billing: XXX';
$lang['payment_rule_two'] = 'Users are not entitled to offset against claims of the operator, unless the counterclaims of the user are legally established or undisputed. The user is also entitled to set off against claims of the operator if the user asserts counterclaims from the same contract. The user may exercise a right of retention only if his counterclaim results from the same contract.';

$lang['liability'] = 'Liability';
$lang['liability_rule_one'] = 'The operator is liable for intentional and grossly negligent breach of duty - for whatever legal reason - in accordance with the statutory provisions.';
$lang['liability_rule_two'] = 'The operator is liable for simple negligence only for damages resulting from the violation of a contractual obligation. Essential contractual obligations are those whose fulfillment makes the proper execution of the contract possible in the first place and on whose compliance the user regularly trusts and can rely. In the event of a breach of essential contractual obligations, the obligation to pay compensation is limited to the damage typically foreseeable at the time the contract was concluded.';

$lang['services'] = 'Services';
$lang['services_info_text'] = 'Information on data protection can be found in the separate privacy policy XXX (Link), which is not part of the contract but complies with the information duties of the DSGVO.';

$lang['amendments'] = 'Amendments';
$lang['amendments_info_text'] = 'These conditions of use can be changed at any time with effectiveness also within the existing contractual relationships. The right of the contracting parties to terminate the contract remains unaffected. If the operator intends to change these terms of use, the operator will inform the user at least 8 weeks before the planned entry into force of the changes. If the user does not object within 6 weeks (objection period) from receipt of the notification of the change, the change shall be deemed to have been validly agreed upon expiry of the opposition period. The objection must be made by e-mail or in writing. The operator will point out this sequence separately in the change notification. If the user exercises his right of objection, the change request is deemed rejected. The contract will then continue without the proposed change.';

$lang['cancellation'] = 'Cancellation';
$lang['cancellation_rule_one_info'] = 'You have the right to enter into this contract within fourteen days without giving any reason. The revocation period is fourteen days from the date of the contract. In order to exercise your right of withdrawal, you must (order network eU, Gewerbepark 1 / Top 16, 5222 Munderfing, E-mail: support@sugarbabe-deluxe.eu) by means of a clear statement (eg a letter sent by mail or e-mail) inform about your decision to withdraw from this contract. You can use the attached model withdrawal form, which is not required. In order to maintain the cancellation period, it is sufficient that you send the notice of the exercise of the right of withdrawal before the expiry of the withdrawal period.';
$lang['cancellation_rule_two'] = 'Consequences of the cancellation';
$lang['cancellation_rule_two_info'] = 'If you withdraw from this Agreement, we have selected all payments we have received from you, including delivery charges (except for the additional costs arising from your choosing a different delivery method than the most favorable standard delivery we offer have to repay immediately and at the latest within fourteen days from the date on which the notification of your revocation of this contract has reached us. For this repayment, we use the same means of payment that you used in the original transaction, unless otherwise agreed with you; In no case will you be charged for this repayment fees. If you have requested that the services be commenced during the period of cancellation, you must pay us a reasonable amount equal to the proportion of services already provided by you at the time you inform us of the exercise of the right of withdrawal in respect of this contract Comparison with the total volume of services provided for in the contract.';
$lang['cancellation_rule_three'] = 'Model withdrawal form (If you want to cancel the contract, please fill out this form and send it back.):';
$lang['on'] = 'On:';
$lang['cancellation_rule_form_one'] = 'I / we (*) hereby revoke the contract concluded by me / us (*) for the purchase of the following goods (*) / the provision of the following service (*)';
$lang['cancellation_rule_form_two'] = 'Ordered on (*) / received on (*):';
$lang['cancellation_rule_form_three'] = 'Name of the consumer (s):';
$lang['cancellation_rule_form_four'] = 'Address of the consumer (s):';
$lang['cancellation_rule_form_five'] = 'Signature of the consumer (s) (only when notified on paper):';
$lang['cancellation_rule_form_six'] = 'Date:';
$lang['cancellation_rule_form_seven'] = '(*) Delete as appropriate.';

$lang['final_provisions'] = 'Final Provisions';
$lang['final_provisions_rule_one'] = 'All legal transactions are governed by Austrian law excluding the UN Sales Convention.';
$lang['final_provisions_rule_two'] = 'Jurisdiction is - as far as legally permissible - Braunau. Regardless, the operator is entitled to sue the user at his general place of jurisdiction.';
$lang['final_provisions_rule_three'] = 'In addition to the ordinary legal process, consumers also have the possibility of settling disputes out of court in accordance with Regulation (EU) No 524/2013. Details can be found there and at the Internet address:';