<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$lang['general_terms_of_use_sugarbabe_deluxe'] = 'Allgemeine Nutzungsbedingungen Sugarbabe Deluxe';

$lang['general'] = 'Allgemeines';
$lang['general_rule_one'] = 'Sugarbabe Deluxe (www.sugarbabe-deluxe.eu - nachfolgend „der Dienst“ genannt) ist ein Dienst der Auftragsnetz e.U., Gewerbepark 1/ Top16, 5222 Munderfing (nachfolgend „der Betreiber“ genannt).';
$lang['general_rule_two'] = 'Mit der Anmeldung bei dem Dienst akzeptiert der Nutzer die vorliegenden Allgemeinen Nutzungsbedingungen für die Nutzung des Dienstes (nachfolgend „die Nutzungsbedingungen“ genannt). Der Betreiber erbringt den Dienst ausschließlich auf der Grundlage der Nutzungsbedingungen in ihrer zum Zeitpunkt der Anmeldung des Nutzers gültigen Fassung.';
$lang['general_rule_three'] = 'Der Dienst, seine Inhalte und die im Rahmen des Dienstes einsehbaren Daten stehen dem Nutzer nur zu rein privaten bzw. nicht kommerziellen Zwecken zur Verfügung. Jede Nutzung zu anderen Zwecken, insbesondere zu gewerblichen oder kommerziellen Zwecken, ist untersagt.';
$lang['general_rule_four'] = 'Nutzer des Dienstes können nur volljährige Personen (ab 18 Jahren) sein. Personen unter 18 Jahren steht der Dienst nicht offen. Mit der Anmeldung beim Dienst versichert der Nutzer, mindestens 18 Jahre alt zu sein.';

$lang['services'] = 'Leistungen';
$lang['services_rule_one'] = 'Der Betreiber bietet dem Nutzer Zugriff auf seine Datenbank. Diese Datenbank ermöglicht dem Nutzer den Aufbau von Partner- und Freundschaften mit anderen Mitgliedern. Außerdem enthält diese Datenbank Profile und Informationen über andere Nutzer. Die Nutzer können sich in der Datenbank die Profile anderer Nutzer ansehen und von diesen in eingeschränktem Maße kontaktiert werden sowie ein eigenes Profil inklusive Foto und bis zu 12 Profilbilder Album, 12 VIP Bilder Album und 12 private Bilder Album anlegen und in die Datenbank einstellen. Der Kunde tritt gegenüber dritten Kunden lediglich unter einem anonymen Wunschnamen auf. Die Nutzer haben auch die Möglichkeit, ihre bereits bestehende kostenlose Mitgliedschaft zu einer kostenpflichtigen "VIP Mitgliedschaft" aufzuwerten. Einem "VIP Mitglied" stehen zusätzlich zu den Funktionen der kostenlosen Basis Mitgliedschaft weitere Funktionen zur Verfügung. So hat ein "VIP Mitglied" unter anderem Zugriff auf das Nachrichtensystem des Dienstes und kann anderen "VIP Mitgliedern" kostenfrei Nachrichten schreiben. Außerdem kann ein "VIP Mitglied" monatlich 12 Basis Mitglieder für den Kontakt freischalten. Die Freischaltung hat eine befristete Laufzeit von einem Monat. Ein uneingeschränkter Zugriff auf das VIP Fotoalbum wird den "VIP Mitgliedern" außerdem ermöglicht.';
$lang['services_rule_two'] = 'Gegenstand des Vertrages ist keine Heiratsvermittlung. Der Betreiber verspricht keine erfolgreiche Kontaktaufnahme zu anderen Nutzern des Dienstes. Leistungsgegenstand ist lediglich die – in Abhängigkeit von der Art der erworbenen Mitgliedschaft unterschiedlich ausgestaltete - Verschaffung der Möglichkeit zur Kontaktaufnahme unter den Nutzern des Dienstes.';

$lang['license_agreement'] = 'Nutzungsvertrag';
$lang['license_agreement_rule_one'] = 'Die Nutzung des Dienstes ist nur nach vorheriger Anmeldung durch den Nutzer und Annahme der Anmeldung durch den Betreiber möglich. Gegenstand der Nutzungsverträge ist jeweils die Nutzung der Dienste durch den Nutzer im Umfang der gewählten Mitgliedschaft. Den Nutzern stehen dabei zwei Varianten der Nutzung des Dienstes bzw. der Mitgliedschaft zur Auswahl: 1. unentgeltliche, eingeschränkte Nutzung des Dienstes im Rahmen der Basismitgliedschaft (nachfolgend „Basismitgliedschaft“ genannt); 2. erweiterte, entgeltliche Nutzung des Dienstes im Rahmen der VIP Mitgliedschaften (nachfolgend „VIP Mitgliedschaften“ genannt). Diese setzt eine zuvor erfolgte Registrierung als Basismitglied voraus. Der Nutzer muss sich zunächst als Basismitglied beim Dienst anmelden. Sodann hat der Nutzer die Möglichkeit, eine entgeltliche VIP Mitgliedschaft zu bestellen. Die Beschreibung der Mitgliedschaften, deren Leistungsumfänge sowie die Preise der VIP Mitgliedschaften sind den Darstellungen im Rahmen des Dienstes zu entnehmen.';
$lang['license_agreement_rule_two'] = 'Die Möglichkeit zur Nutzung des angebotenen Dienstes bzw. die Möglichkeit der Anmeldung bzw. Registrierung zu dem Dienst – gleich ob kostenlos (Basismitgliedschaft) oder kostenpflichtig (VIP Mitgliedschaft) – ist jeweils unverbindlich und stellt insbesondere kein verbindliches Angebot des Betreibers auf Abschluss eines entsprechenden Nutzungsvertrages dar. Vielmehr ist darin eine Aufforderung an den Nutzer zur Abgabe eines Angebots auf Abschluss eines Nutzungsvertrages zu sehen. Mit Abschluss des jeweiligen Anmelde- bzw. Bestellvorgangs durch den Nutzer auf dem Internet-Portal des Dienstes gibt dieser ein verbindliches Angebot auf Abschluss des Vertrages (Basismitgliedschaft oder VIP Mitgliedschaft) über die Nutzung des Dienstes ab. Der Betreiber kann dieses Angebot des Nutzers durch gesonderte E-Mail oder durch Bereitstellung des entsprechenden Dienstes innerhalb von drei Werktagen annehmen, andernfalls ist der Nutzer nicht mehr an sein Angebot gebunden. Erst durch diese Annahme kommt der Vertrag zwischen dem Nutzer und dem Betreiber zustande. Der Betreiber ist nicht zum Vertragsschluss verpflichtet. Der Betreiber kann die Annahme der Anmeldung bzw. Bestellung (Abschluss des Vertrages) ohne Angabe von Gründen ablehnen.';

$lang['rights_and_obligations'] = 'Rechte und Pflichten';
$lang['rights_and_obligations_rule_one'] = 'Bei der Anmeldung zur Basismitgliedschaft, der Bestellung einer VIP Mitgliedschaft sowie der Anlage des Nutzerprofils werden verschiedene Angaben des Nutzers abgefragt. Dabei kann es sich sowohl um Pflichtangaben als auch um optionale Angaben handeln. Der Nutzer versichert, dass die von ihm gemachten Angaben in jedem Fall vollständig und richtig sind, und dass insbesondere die von ihm hinterlegten Kontaktdaten gültig und ihm zugeordnet sind. Der Nutzer ist verpflichtet, Änderungen bezüglich der von ihm gemachten Pflichtangaben unverzüglich selber im Profil anzupassen.';
$lang['rights_and_obligations_rule_two'] = 'Es ist Nutzern untersagt, die Zugangsdaten Dritten mitzuteilen oder Dritten die Nutzung der Dienste mit Zugangsdaten des Nutzers zu ermöglichen. Der Nutzer ist verpflichtet, seine Zugangsdaten für die Nutzung des Dienstes generell geheim zu halten. Sofern für den Nutzer begründeter Anlass zur Vermutung besteht, dass ein Dritter Kenntnis von seinen Zugangsdaten erlangt haben könnte, hat er den Betreiber unverzüglich hierüber in Kenntnis zu setzen und sein Passwort zu ändern.';
$lang['rights_and_obligations_rule_three'] = 'Der Nutzer hat folgendes zu unterlassen:';
$lang['rights_and_obligations_rule_three_one'] = 'Die Veröffentlichung von Inhalten, gleich welcher Art, die gegen gel¬ten¬des Recht ver-sto¬ßen, Rechte Drit¬ter ver¬let¬zen oder gegen die Grund¬sätze des Jugend¬schut¬zes ver-sto¬ßen; ins¬be¬son¬dere:';
$lang['rights_and_obligations_rule_three_one_one'] = 'Die Ver¬wen¬dung von Inhal¬ten, durch die andere Nutzer oder Dritte belei¬digt oder ver¬leum¬det wer¬den;';
$lang['rights_and_obligations_rule_three_one_two'] = 'Die Nut¬zung, das Bereit¬stel¬len und das Ver¬brei¬ten von Inhal¬ten, Diens¬ten und/oder Pro¬duk¬ten, die gesetz¬lich geschützt oder mit Rech¬ten Drit¬ter (z.B. Urhe¬ber¬rechte) belas¬tet sind, ohne hierzu aus¬drück¬lich berech¬tigt zu sein;';
$lang['rights_and_obligations_rule_three_one_three'] = 'As Ein¬stel¬len, die Ver¬brei¬tung, das Ange¬bot und die Bewer¬bung por¬no¬gra¬fi¬scher, gegen Jugend¬schutz¬ge¬setze, gegen Daten¬schutz¬recht und/oder gegen sons¬ti¬ges Recht ver¬sto¬ßen¬der und/oder betrü¬ge¬ri¬scher Inhalte, Dienste und/oder Pro¬dukte. ';
$lang['rights_and_obligations_rule_three_two'] = 'Unab¬hän¬gig von einem even¬tu¬el¬len Geset¬zes¬ver¬stoß bei der Ein¬stel¬lung eige¬ner Inhalte im Rahmen des Dienstes sowie bei der Kom¬mu¬ni¬ka¬tion mit ande¬ren Nutzern (z.B. durch Ver¬sen¬dung per¬sön¬li¬cher Mit¬tei¬lun¬gen, durch die Teil¬nahme an Dis¬kus¬si-ons¬fo¬ren oder das Ver¬fas¬sen von Gäs¬te¬buchein¬trä¬gen) die fol¬gen¬den Akti¬vi¬tä¬ten:';
$lang['rights_and_obligations_rule_three_two_one'] = 'Auf¬for¬de¬rung an ande¬re Nutzer zur Preis¬gabe von Kenn¬wör¬tern oder per¬so¬nen¬be-zo¬ge¬ner Daten für kom¬mer¬zi¬elle oder rechts- bzw. geset¬zes¬wid¬rige Zwe¬cke;';
$lang['rights_and_obligations_rule_three_two_two'] = 'Beläs¬ti¬gung ande¬rer Teil¬neh¬mer, z.B. durch mehr¬fa¬ches per¬sön¬li¬ches Kon¬tak¬tie¬ren ohne oder ent¬ge¬gen der Reak¬tion des ande¬ren Nutzers sowie das För¬dern bzw. Unter¬stüt¬zen der¬ar¬ti¬ger Beläs¬ti¬gun¬gen;';
$lang['rights_and_obligations_rule_three_two_three'] = 'Ver¬brei¬tung und/oder öffent¬li¬che Wie¬der¬gabe bzw. Zugänglichmachung von im Rahmen des Dienstes ver¬füg¬ba¬ren Inhal¬ten, soweit dies nicht aus¬drück¬lich vom jewei¬li¬gen Urhe¬ber gestat¬tet oder als Funk¬tio¬na¬li¬tät im Rahmen des Dienstes aus-drück¬lich zur Ver¬fü¬gung gestellt wird;';
$lang['rights_and_obligations_rule_three_two_four'] = 'Ver¬brei¬tung anstö¬ßi¬ger, sexu¬ell gepräg¬ter, obszö¬ner oder dif¬fa¬mie¬ren¬der Inhalte bzw. Kom¬mu¬ni¬ka¬tion sowie sol¬cher Inhalte bzw. Kom¬mu¬ni¬ka¬tion die geeig¬net sind/ist, Ras¬sis¬mus, Fana¬tis¬mus, Hass, kör¬per¬li¬che Gewalt oder rechts¬wid¬rige Hand¬lun¬gen zu för¬dern bzw. zu unter¬stüt¬zen (jeweils expli¬zit oder impli¬zit);';
$lang['rights_and_obligations_rule_three_two_five'] = 'Ver¬brei¬tung von Viren, Tro¬ja¬nern und ande¬ren schäd¬li¬chen Dateien;';
$lang['rights_and_obligations_rule_three_two_six'] = 'Ver¬sen¬dung von Junk- oder Spam-Mails sowie von Ket¬ten¬brie¬fen.';
$lang['rights_and_obligations_rule_three_two_seven'] = 'Die im Rahmen des Dienstes für andere Nutzer des Dienstes sichtbare Wiedergabe, Einblendung oder sonstige Angabe von Kontaktdaten (z.B. Telefonnummer, Anschriften, E-Mail-Adressen, etc.) oder sonstigen Informationen (z.B. Links zu Profilen des Nutzers auf anderen sozialen Netzwerken oder sonstigen Diensten, Nutzernamen auf anderen sozialen Netzwerken oder sonstigen Diensten, etc.), die zur Kontaktaufnahme zwischen Nutzern des Dienstes unter Umgehung des Dienstes bzw. seiner Benachrichtigungssysteme dienen können.';
$lang['rights_and_obligations_rule_three_three'] = 'Jede Hand¬lung, die geeig¬net ist, den rei¬bungs¬lo¬sen Betrieb des Dienstes zu beein¬träch¬ti-gen, ins¬be¬son¬dere die Sys¬teme des Betreibers über¬mä¬ßig zu belas¬ten.';
$lang['rights_and_obligations_rule_three_four'] = 'Jegliche Nutzung des Dienstes, seiner Inhalte oder der im Rahmen des Dienstes einsehbaren Daten zu gewerblichen oder kommerziellen Zwecken, insbesondere jegliche Kontaktaufnahme mit oder die sonstige Ansprache von anderen Nutzern des Dienstes im Rahmen des Dienstes zu vorgenannten Zwecken.';
$lang['rights_and_obligations_rule_three_five'] = 'Inhalte des Dienstes oder Daten der Nutzer des Dienstes systematisch auszulesen oder zu kopieren oder sonst zu exportieren, um sie außerhalb des Dienstes zu nutzen.';

$lang['availability'] = 'Verfügbarkeit';
$lang['availability_info_text'] = 'Sofern für den Betreiber absehbar ist, dass Ausfallzeiten für Wartung und Software-Updates länger als 2 Stunden dauern, wird der Anbieter dies dem Kunden mindestens 2 Kalendertage vor Beginn der jeweiligen Arbeiten mitteilen. Grundsätzlich ist der Dienst durchgehend 24 Stunden, sieben Tage die Woche einsatzfähig mit einer Verfügbarkeit von 99 % im Monatsmittel. Hiervon ausgenommen sind Ausfallzeiten durch Wartung und Software-Updates sowie Zeiten, in denen der Webserver aufgrund von technischen oder sonstigen Problemen, die nicht im Einflussbereich des Betreibers liegen (höhere Gewalt, Verschulden Dritter etc.), über das Internet nicht zu erreichen ist.';

$lang['content'] = 'Inhalte';
$lang['content_rule_one'] = 'Der Nutzer ist für die von ihm ein¬ge¬stell¬ten Inhalte allein und voll ver¬ant¬wort¬lich. Der Betreiber über¬nimmt keine Über¬prü¬fung der Inhalte auf Voll¬stän¬dig¬keit, Rich¬tig¬keit, Recht¬mä¬ßig¬keit, Aktua¬li¬tät, Qua¬li¬tät und Eig¬nung für einen bestimm¬ten Zweck. Der Nutzer versichert gegenüber dem Betreiber und steht dafür ein, dass er alleiniger Verfügungsberechtigter hinsichtlich der von ihm eingestellten Inhalte ist, insbesondere, dass er berechtigt ist, dem Betreiber die hier eingeräumten Rechte einzuräumen und dass er keine der vertragsgegenständlichen Rechteeinräumung entgegenstehende Verfügung getroffen hat oder treffen wird. Der Nutzer stellt den Betreiber von allen Ansprüchen Dritter im Zusammenhang mit der vertragsgemäßen Nutzung der Inhalte frei, einschließlich der Kosten angemessener Rechtsverteidigung, hilfsweise entschädigt er ihn. Dies gilt nicht, soweit der Nutzer die Rechtsverletzung nicht zu vertreten hat.';
$lang['content_rule_two'] = 'Der Betreiber behält sich das Recht vor, das Ein¬stel¬len von Inhal¬ten durch den Nutzer abzu-leh¬nen und/oder bereits ein¬ge¬stellte Inhalte (ein¬schließ¬lich pri¬va¬ter Nach¬rich¬ten, Gäs¬te-buchein¬träge und sonstiger Mitteilungen) ohne vor¬he¬rige Ankün¬di¬gung zu bear¬bei¬ten, zu sper-ren oder zu ent¬fer¬nen, sofern das Ein¬stel¬len der Inhalte durch den Nutzer oder die ein¬ge¬stell-ten Inhalte selbst zu einem Ver¬stoß gegen diese Nutzungsbedingungen geführt haben oder kon¬krete Anhalts¬punkte dafür vor¬lie¬gen, dass es zu einem schwer¬wie¬gen¬den Ver¬stoß gegen diese Nutzungsbedingungen kom¬men wird. Der Betreiber wird hier¬bei jedoch auf die berech-tig¬ten Inter¬es¬sen des Nutzers Rück¬sicht neh¬men und das mil¬deste Mit¬tel zur Abwehr des Ver-sto¬ßes wäh¬len.';
$lang['content_rule_three'] = 'Mit dem Ein¬stel¬len von Inhal¬ten im Rahmen des Dienstes räumt der Nutzer dem Betreiber jeweils ein unent¬gelt¬li¬ches und über¬trag¬ba¬res Nut¬zungs¬recht an den jewei¬li¬gen Inhal¬ten ein, ins¬be¬son¬dere.';
$lang['content_rule_three_one'] = 'zur Spei¬che¬rung der Inhalte auf dem Ser¬ver des Betreibers sowie deren Ver¬öf¬fent¬li-chung, ins¬be¬son¬dere deren öffent¬li¬cher Zugäng¬lich¬ma¬chung (z.B. durch Anzeige der Inhalte im Internet im Rahmen des Dienstes),';
$lang['content_rule_three_two'] = 'zur Bear¬bei¬tung und Ver¬viel¬fäl¬ti¬gung, soweit dies für die Vor¬hal¬tung bzw. Ver¬öf¬fent¬li-chung der jewei¬li¬gen Inhalte erfor¬der¬lich ist, und';
$lang['content_rule_three_three'] = 'zur Ein¬räu¬mung von - auch ent¬gelt¬li¬chen - Nut¬zungs¬rech¬ten gegen¬über Drit¬ten an Inhal¬ten im Rahmen der Nutzung des Dienstes.';
$lang['content_rule_three_four'] = 'Das vorstehende Nutzungsrecht erlischt wenn und sobald der Nutzer die von ihm eingestellten Inhalte wie¬der vom Dienst entfernt. Der Betreiber bleibt jedoch berechtigt, zu Siche¬rungs- und/oder Nach¬weis¬zwe¬cken erstellte Kopien der Inhalte auf¬zu¬be¬wah¬ren. Die dritten Nutzer an vom Nutzer eingestellten Inhalten zuvor ein¬ge¬räum¬ten Nut¬zungs¬rechte blei-ben eben¬falls unbe¬rührt.';

$lang['duration_and_termination'] = 'Dauer und Beendigung';
$lang['duration_and_termination_rule_one'] = 'Die Basismitgliedschaft läuft auf unbestimmte Zeit und kann vom Nutzer jeder¬zeit gekün¬di¬gt werden. Der Betreiber kann die Basismitgliedschaft unter Einhaltung einer Kündigungsfrist von 14 Kalendertagen zum Monatsende kündigen';
$lang['duration_and_termination_rule_two'] = 'Die VIP Mitgliedschaften werden mit Laufzeiten von 1, 3 und 6 Monaten angeboten. Einzelheiten sind der jeweiligen Produktbeschreibung zu entnehmen. Bei der VIP Mitgliedschaft mit 1-monatiger Laufzeit verlängert sich die Mitgliedschaft jeweils um einen weiteren Monat, wenn der Nutzer die Mitgliedschaft nicht spätestens bis 24 Stunden vor Ablauf der Mitgliedschaft (einschließlich optionaler Verlängerungszeiträume) schriftlich per Email oder in dem Nutzerprofil per Klick auf den Kündigungsbutton kündigt bzw. der Betreiber nicht spätestens 3 Kalendertage vor Ablauf der Mitgliedschaft (einschließlich optionaler Verlängerungszeiträume) schriftlich, per Email kündigt. Bei VIP Mitgliedschaften von mehr als einem Monat anfänglicher Laufzeit (3 und 6 Monate) verlängert sich die Mitgliedschaft jeweils um den ursprünglich gebuchten Zeitraum (3 bzw. 6 Monate), wenn der Nutzer die Mitgliedschaft nicht spätestens bis 1 Woche vor Ablauf der Mitgliedschaft (einschließlich optionaler Verlängerungszeiträume) schriftlich per Email oder in dem Nutzerprofil per Klick auf den Kündigungsbutton kündigt bzw. der Betreiber nicht spätestens 2 Wochen vor Ablauf der Mitgliedschaft (einschließlich optionaler Verlängerungszeiträume) schriftlich per Email kündigt. Maßgeblich für den Beginn der Mitgliedschaft ist Annahme der Anmeldung des Nutzers durch den Betreiber (Vertragsschluss).';
$lang['duration_and_termination_rule_three'] = 'Das Recht der Parteien, den Vertrag aus wichtigem Grund zu kündigen, wird durch vorstehende Kündigungsregelungen nicht berührt.';
$lang['duration_and_termination_rule_four'] = 'Mit Wirk¬sam¬wer¬den der Kün¬di¬gung endet das Ver¬trags¬ver¬hält¬nis und der Nutzer darf den vertragsgemäßen Zugang nicht mehr nut¬zen. Der Betreiber ist berechtigt, den Benut¬zer¬na-men sowie das Pass¬wort mit Wirk¬sam¬wer¬den der Kün¬di¬gung zu sper¬ren.';
$lang['duration_and_termination_rule_five'] = 'Der Betreiber ist berech¬tigt, mit Ablauf von 30 Kalendertagen nach Wirk¬sam¬wer¬den der Kün-di¬gung und nach Ablauf etwai¬ger gesetz¬li¬cher Vor¬hal¬tungs¬fris¬ten sämt¬li¬che im Rah¬men der Nutzung des Dienstes durch den Nutzer ent¬stan¬de¬ne Daten unwie¬der¬bring¬lich zu löschen.';

$lang['blocking'] = 'Sperrung';
$lang['blocking_rule_one'] = 'Wenn der Nutzer gegen diese Nut¬zungs¬be¬din¬gun¬gen und/oder gel¬ten¬des Recht ver¬stößt bzw. ver¬sto¬ßen hat, oder wenn der Betreiber ein sons¬ti¬ges berech¬tig¬tes Inter¬esse an der Sper¬rung hat, kann der Betreiber den Zugang des Nutzers zum Dienst vor¬über¬ge¬hend oder dau¬er¬haft sper¬ren. Bei der Ent¬schei¬dung über eine Sper¬rung wird der Betreiber die berech¬tig¬ten Inter¬es-sen des Nutzers ange¬mes¬sen berück¬sich¬ti¬gen.';
$lang['blocking_rule_two'] = 'Bei einer vor¬über¬ge¬hen¬den bzw. dau¬er¬haf¬ten Sper¬rung sperrt der Betreiber die Zugangs¬be-rech¬ti¬gung und benach¬rich¬tigt den Nutzer hier¬über per E-Mail.';
$lang['blocking_rule_three'] = 'Bei einer Bei einer vor¬über¬ge¬hen¬den Sper¬rung reak¬ti¬viert der Betreiber nach Ablauf der Sperr¬zeit die Zugangs¬be¬rech¬ti¬gung und benach¬rich¬tigt den Nutzer hier¬über per E-Mail. Eine dau¬er¬haft gesperrte Zugangs¬be¬rech¬ti¬gung kann nicht wie¬der¬her¬ge¬stellt wer¬den. Dau¬er¬haft gesperrte Nutzer sind von der Teil¬nahme am Dienst dau¬er¬haft aus¬ge¬schlos¬sen und dür¬fen sich nicht erneut beim Dienst anmel¬den.';

$lang['payment'] = 'Zahlung';
$lang['payment_rule_one'] = 'Zur Zahlung stehen dem Nutzer folgende Zahlungsarten zur Verfügung:';
$lang['payment_rule_one_one'] = 'Sofortüberweisung: Am Ende der Buchung wird der Nutzer auf das sichere SOFORT Zahlungsformular zur Durchführung der Überweisung weitergeleitet. Eine Registrierung ist nicht erforderlich. Die Daten werden verschlüsselt übertragen und die Überweisung wird direkt durchgeführt.';
$lang['payment_rule_one_two'] = 'Lastschriftverfahren: Beim Lastschriftverfahren wird der Rechnungsbetrag einfach und bequem unter Verwendung der vom Nutzer angegebenen Kontodaten innerhalb von acht Arbeitstagen vom Konto abgebucht. Als Zahlungsempfänger wird auf der Abrechnung angezeigt: „Auftragsnetz e.U.“';
$lang['payment_rule_one_three'] = 'Kreditkarte: Der Betreiber akzeptiert Visa, Mastercard. Die Kreditkarte wird mit Abschluss des Vertrages (Annahme der Anmeldung) belastet. Als Zahlungsempfänger wird auf der Abrechnung angezeigt: XXX';
$lang['payment_rule_two'] = 'Nutzer sind nicht berechtigt, gegenüber Forderungen des Betreibers aufzurechnen, es sei denn, die Gegenansprüche des Nutzers sind rechtskräftig festgestellt oder unbestritten. Der Nutzer ist zur Aufrechnung gegenüber Forderungen des Betreibers auch berechtigt, wenn der Nutzer Gegenansprüche aus demselben Vertrag geltend macht. Der Nutzer darf ein Zurückbehaltungsrecht nur dann ausüben, wenn sein Gegenanspruch aus demselben Vertrag herrührt.';

$lang['liability'] = 'Haftung';
$lang['liability_rule_one'] = 'Der Betreiber haftet bei vorsätzlicher und grob fahrlässiger Pflichtverletzung – gleich aus welchem Rechtsgrund – gemäß den gesetzlichen Bestimmungen.';
$lang['liability_rule_two'] = 'Der Betreiber haftet bei einfacher Fahrlässigkeit nur für Schäden aus der Verletzung einer vertragswesentlichen Pflicht. Vertragswesentliche Pflichten sind solche, deren Erfüllung die ordnungsgemäße Durchführung des Vertrages überhaupt erst ermöglichen und auf deren Einhaltung der Nutzer regelmäßig vertraut und vertrauen darf. Im Falle der Verletzung wesentlicher Vertragspflichten ist die Ersatzpflicht auf den bei Vertragsschluss vorhersehbaren, typischerweise eintretenden Schaden begrenzt.';

$lang['services'] = 'Leistungen';
$lang['services_info_text'] = 'Hinweise zum Datenschutz finden sich in der separaten Datenschutzerklärung XXX (Link), welche nicht Vertragsbestandteil ist, sondern die Info-Pflichten der DSGVO erfüllt.';

$lang['amendments'] = 'Änderungen';
$lang['amendments_info_text'] = 'Diese Nutzungsbedingungen können jederzeit mit Wirksamkeit auch innerhalb der bestehenden Vertragsverhältnisse geändert werden. Das Recht der Vertragspartner zur Kündigung des Vertrages bleibt hiervon unberührt. Sofern der Betreiber eine solche Änderung dieser Nutzungsbedingungen beabsichtigt, wird der Betreiber den Nutzer hierüber mindestens 8 Wochen vor dem geplanten Inkrafttreten der Änderungen in Kenntnis setzen. Sofern der Nutzer nicht innerhalb von 6 Wochen (Widerspruchsfrist) ab Zugang der Mitteilung der Änderung widerspricht, gilt die Änderung ab Ablauf der Widerspruchsfrist als wirksam vereinbart. Der Widerspruch hat per E-Mail oder schriftlich zu erfolgen. Der Betreiber wird auf diese Folge in der Änderungsmitteilung gesondert hinweisen. Übt der Nutzer sein Widerspruchsrecht aus, gilt der Änderungswunsch als abgelehnt. Der Vertrag wird dann ohne die vorgeschlagene Änderung fortgesetzt.';

$lang['cancellation'] = 'Widerrufsbelehrung';
$lang['cancellation_rule_one_info'] = 'Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsabschlusses. Um Ihr Widerrufsrecht auszuüben, müssen Sie uns (Auftragsnetz e.U., Gewerbepark 1/ Top 16, 5222 Munderfing, E-Mail: support@sugarbabe-deluxe.eu) mittels einer eindeutigen Erklärung (z.B. ein mit der Post versandter Brief oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das beigefügte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist. Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.';
$lang['cancellation_rule_two'] = 'Folgen des Widerrufs';
$lang['cancellation_rule_two_info'] = 'Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet. Haben Sie verlangt, dass die Dienstleistungen während der Widerrufsfrist beginnen soll, so haben Sie uns einen angemessenen Betrag zu zahlen, der dem Anteil der bis zu dem Zeitpunkt, zu dem Sie uns von der Ausübung des Widerrufsrechts hinsichtlich dieses Vertrags unterrichten, bereits erbrachten Dienstleistungen im Vergleich zum Gesamtumfang der im Vertrag vorgesehenen Dienstleistungen entspricht.';
$lang['cancellation_rule_three'] = 'Muster-Widerrufsformular  (Wenn Sie den Vertrag widerrufen wollen, dann füllen Sie bitte dieses Formular aus und senden Sie es zurück.):';
$lang['on'] = 'An:';
$lang['cancellation_rule_form_one'] = 'Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*)/die Erbringung der folgenden Dienstleistung (*)';
$lang['cancellation_rule_form_two'] = 'Bestellt am (*)/erhalten am (*): ';
$lang['cancellation_rule_form_three'] = 'Name des/der Verbraucher(s): ';
$lang['cancellation_rule_form_four'] = 'Anschrift des/der Verbraucher(s): ';
$lang['cancellation_rule_form_five'] = 'Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier):';
$lang['cancellation_rule_form_six'] = 'Datum:';
$lang['cancellation_rule_form_seven'] = '(*) Unzutreffendes streichen.';

$lang['final_provisions'] = 'Schlussbestimmungen';
$lang['final_provisions_rule_one'] = 'Für sämtliche Rechtsgeschäfte gilt österreichisches Recht unter Ausschluss des UN-Kaufrechtes. ';
$lang['final_provisions_rule_two'] = 'Gerichtsstand ist – soweit gesetzlich zulässig – Braunau. Ungeachtet dessen ist der Betreiber berechtigt, den Nutzer an seinem allgemeinen Gerichtsstand zu klagen.';
$lang['final_provisions_rule_three'] = 'Neben dem ordentlichen Rechtsweg besteht für Verbraucher auch die Möglichkeit einer außergerichtlichen Beilegung von Streitigkeiten gemäß Verordnung (EU) Nr. 524/2013. Einzelheiten dazu finden sich dort und unter der Internetadresse:';